### ISSUE TITLE
Mod2 / Lab 1B, Exercise 18 Process the batch order / Step 8 - ISSUE - UNABLE TO PROCEED AND COMPLETE

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing#53]
# Module: 2, lab 1B
#### Step: 08

Description of issue
![image](https://user-images.githubusercontent.com/89986870/188820937-dd42fe4f-5d08-456d-8094-905af19bb3e6.png)

Repro steps:

1. There are no lines in the picking list, this is because of the error that not enough capacity could be found for the order. Please clarify how to fix this.

**Comment by chaast** [comment]
I went back to this exercise today. i noticed on the picking list page (step 7) i was able to select the option to create picking list lines... then when i opened the corresponding picking list, and i could see the lines for this part - but i then had the issue showing on the screenshot below, hence I was still unable to proceed...  

Please note: inventory was greyed out, hence i was unable to proceed with step 10.

![image](https://user-images.githubusercontent.com/89986870/190895029-4c989d32-dcae-4f4a-88bf-486d79085f5a.png)

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by mstall1ngs** [comment]
Thanks for reporting this on GitHub! Module 2 / Case study 1B / Exercises 18. We are reviewing this and will provide an update once a resolution is in place.

**Comment by mstall1ngs** [comment]
There are several reasons why the scheduling engine might fail and issue this error message. If the error occurs during operation scheduling, you must make sure that a calendar is associated with all applicable resource groups. In operation scheduling, the resource group's calendar is used to determine the start and end times and dates for each operation. It also limits the amount of time that the system can schedule for one specific operation for one specific day in one specific resource group.

Here's guidance on the root cause of the error: 

- The error can occur if no applicable resources satisfy the operation requirements at the production order site.
          - Review the applicable resources 
                 - Go to Production control > Production orders > All production orders, and open or select the production order that can't be scheduled.
                 - On the Production order tab, in the Production details group, select Route.
                 - On the Production route page, select the operation, and then, on the Action Pane, select Applicable resources.
                 - Ensure that the Use requirements field is set to Operations scheduling or Job scheduling, depending on the type of scheduling that you're using.
-  The error can occur if no calendar is associated with the resource or resource group, or if the associated calendar isn't correctly set up (for example, it has no working times, or its efficiency as a percentage is 0 [zero]). 
         - Verify that a calendar is associated with the resource or resource group
                - The calendar is using a 24hr Production. Ensure that working times are composed.
                - Follow the steps above but when on the Applicable Resources page, select View resource 
                - On the Resources page or the Resource groups page, on the Calendars FastTab, make sure that a calendar is associated with the resource or resource group 
         - Review the setup of the calendar
                - Go to Organization administration > Setup > Calendars > Calendars, and select the calendar that is associated with the resource or resource group.
                - On the Action Pane, select Working times.
                - On the Working times page, make sure that the page isn't blank. Additionally, for the days that you're interested in, make sure that the Control field isn't set to Closed, working times exist, and the Efficiency is percentage field isn't set to 0 (zero).
- The error can occur when you perform finite scheduling, but there's no free capacity.
- Review the available capacity on the resource and resource group


I was able to test this issue to release status.

![image](https://user-images.githubusercontent.com/104943975/221393409-9bd2d457-47fe-46fc-a189-5beea1cdaefa.png)
